### ISSUE TITLE
Fix paste in mintty

### ISSUE THREAD

**Issue by theimpostor** [theimpostor/osc#13]
mintty responds to paste requests with the clipboard parameter empty which is a valid response (e.g. `"\x1b]52;;"`, however osc expects exactly one character there (it strips the first 7 bytes of the response), and thus the data argument is corrupted.

First reported here: https://github.com/mintty/mintty/issues/1264#issuecomment-2471356648

**Comment by theimpostor** [comment]
@Kreijstal can you please try now with the latest release (https://github.com/theimpostor/osc/releases/tag/v0.4.5).

**Comment by Kreijstal** [comment]
Alright

**Comment by theimpostor** [comment]
This appears to working.
