### ISSUE TITLE
Option to use primary selection instead of clipboard

### ISSUE THREAD

**Issue by Lenbok** [theimpostor/osc#14]
It would be great it this tool had an option to let you get/set the primary selection instead of the clipboard. OSC allows this by specifying the "Pc" parameter as "p" instead of "c" (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands).

**Comment by theimpostor** [comment]
Added the option but I don't have a good way of testing, @Lenbok please try it out and let me know.

**Comment by Lenbok** [comment]
Seems to work perfectly, thanks!
