### ISSUE TITLE
[kitty] paste hangs when the permission hasn't been set

### ISSUE THREAD

**Issue by NightMachinery** [theimpostor/osc#2]
When I do `osc52 --paste` that terminal tab hangs. If I manually kill `osc52`, the shell in that tab will resume but need `reset` to display program outputs properly.

Things work correctly if kitty is configured to allow pasting.

It would be good if `osc52` displayed an error instead of hanging.

**Comment by theimpostor** [comment]
Should be fixed now with v0.2.2
